version: '3.8'

services:
  db:
    # This image includes PostgreSQL 16 pre-installed with the pgvector extension!
    image: pgvector/pgvector:pg16
    container_name: paperfind-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paperfind
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: paperfind_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
